### ISSUE TITLE
Steps for running

### ISSUE THREAD

**Issue by wyxos** [PieterScheffers/docker-spectron#1]
Sorry for asking this here, I am kind of new to Docker, would it be possible to include steps in the Readme.md on how to get the image running against an existing project?

**Comment by PieterScheffers** [comment]
No problem. It just has been a while that I used this. It provides an `xvfb` for the Electron (for usage in a CI environment). I was using [drone.io](https://drone.io/) at the time. I would use this to run the tests for the Electron app. `xvfb` provides a fake 'screen' for the application. So to use, you would have some Spectron tests. Then to run you would mount your code in this image with Docker. Then you can run the tests of Spectron.

**Comment by wyxos** [comment]
Thanks. My question/request may not be related to your image but rather to the mounting part I think. I am getting confused between DockerFile and docker-compose.yml, and so many commands.

So assuming I have a simple electron structure
````
- project
  - index.js
  - index.html
  - tests/
    - features
      - app.spec.js
  - package.json
````


And I wanted the tests via docker. So from your notes, I need to wrap my head around "how to mount local code into an image"? Really sorry if this is sounding more of docker assistance than the image itself. I've spent two days trying to understand docker but it's still not getting through.

**Comment by PieterScheffers** [comment]
Ok you got some learning to do then 😉
If you want to test the application, take the following steps:
1. Download or clone this repo (`git clone https://github.com/PieterScheffers/docker-spectron.git`)
2. Build a Docker image with the Dockerfile from this repo
```
cd docker-spectron
docker build -t PieterScheffers/docker-spectron .
```
3. Run your tests in this Docker container
```
cd path/to/your/electron/code
docker run -it --rm -v $(pwd):/usr PieterScheffers/docker-spectron sh -c "cd /usr && npm test"
```

This last command would run the docker-spectron image. It will mount your local directory (in pwd eg. the current working directory) into the container so you can run your tests in this container.

**Comment by wyxos** [comment]
Thank you for taking the time to provide these steps.

After spending two days hitting my head around, I kind of began understanding the order and commands to use before your response.

So ```docker pull pieterscheffers/docker-spectron``` allows to pull an image (and avoids having to use git clone manually as you mentioned).

In fact, docker is smart enough that, if I were to run the last command alone while the image not being present on my end, it would attempt to download it first.

For powershell, apparently it's ${pwd} instead of $(pwd). I have no idea what pwd means but meh it almost did work. Your image did have a set of errors on built (I also attempted manually as per your instructions) which I assume is obviously due to the age:
````
E: Unable to locate package gcc-4.8-multilib
E: Couldn't find any package by glob 'gcc-4.8-multilib'
E: Couldn't find any package by regex 'gcc-4.8-multilib'
E: Unable to locate package g++-4.8-multilib
E: Couldn't find any package by glob 'g++-4.8-multilib'
E: Couldn't find any package by regex 'g++-4.8-multilib'
````
And even if I ignore these I get this error from running the last command ```` standard_init_linux.go:207: exec user process caused "no such file or directory" ````

Eventually, the steps you provided hinted me in the right direction, so I attempted the same by using the image electronuserland/builder:wine which, as specified in electron builder dock, is meant for headless testing, and changed the mounting path to /app, however, even if the test command seems to execute, the spectron test which works fine on Windows doesn't work in docker (promise is not resolved), and a bunch of other issues.

All of this to say, I tried hard to understand docker and this concept in hope that:
- I would not have to endure seeing the app opening 100 times if I wrote 100 e2e tests
- would make the tests a bit faster
- avoid the bug of "empty terminals opening on Windows" when using spectron

But from the looks of it, it solves only the last issue and brings a lot of new issues.

I decided to log my adventure in case someone else also struggles at achieving what I attempted here. But thanks again for the steps you provided, for they clarified the idea/concept of docker a bit further in my mind.

**Comment by PieterScheffers** [comment]
Ah you mention `electronuserland/builder:wine`! I think I also used that one for testing. I have found the drone.yml I used for testing the Electron app. The commands in this example are the same as when you run a shell in the docker container and then run these commands. Like:
```
docker run -it --rm electronuserland/electron-builder:wine bash
# And then on the bash shell run the commands in the following drone.yml
```

Example `drone.yml`
```
pipeline:

  install:
    image: electronuserland/electron-builder:wine
    pull: true
    commands:
      - cd app
      - yarn install

  test:
    image: electronuserland/electron-builder:wine
    environment:
      - DISPLAY=:99
      - NODE_ENV=test
    commands:
      - Xvfb :99 -ac &
      - sleep 5
      - cd app
      - npm test

  dist:
    image: electronuserland/electron-builder:wine
    commands:
      - npm install
      - npm prune
      - node build.js
      - ls -la dist
```

P.s. `pwd` returns the current working directory 😉

I must say that I used it in a drone CI on a Ubuntu VM. So I don't know the problems you would encounter on Windows. But to solve the problems you describe there will probably be some solutions in spectron. Like for faster testing maybe you can make the tests run in parallel. And if you write the tests more like when you are a user (So doing all steps through your app), then the app doesn't have to be started as much. Of course that makes your tests more brittle because you can't tests all cases as easily. But for some end-to-end tests is suffices.

**Comment by wyxos** [comment]
Thanks again a lot for your guidance. I appreciate it.

In regards to your notes, drone CI, is this similar to Circle CI, or Appvoyer? I have an understanding that these services are online and that, if you are to run your tests, you have to first commit, and then run them? Or am I wrong?

And yeah, you did mention that pwd returns the current directory, but I don't understand how, where does it come from =/ is this a Unix/CLI thing?

As for the issues: parallel tests, I've tried some with AVA, and I encounter the issue you mentioned. When I said the tests are slow, I was basing on one test, for example, just a spectron test to get the window count and evaluate if a text is present on the initial screen takes between 7-10 seconds. That's quite a lot...

So for the time being, I am limiting to one test in spectron that just tests that the app launches, and all other tests will be unit tests unless I find it relevant to test an actual scenario in e2e. That way when Jest runs on watch, it won't re-run the spectron test if no changes are made and focus on tests which I amend.

Do you by any chance have figures of how long one simple spectron test under headless mode would take to run on your end?  But I am unable to fully understand docker for laravel development, so I have to turn of Hyper-V and go back to VM/homestead when I have to work. I'll try again the above next time I switch docker on.
